### PR TITLE
added my cccbauer environment

### PR DESCRIPTION
**Pull request by cccbauer**

### CODE REVIEW

**Comment by satra** [comment]
could you please merge with current master and push again?

**Comment by cccbauer** [comment]
Ok, I merged and pushed again!

**Comment by satra** [comment]
did you fetch current master?

git fetch upstream
git merge upstream/master

(at this point you will have conflicts that you would need to fix)

git add conflicted file
git commit -am "fixed conflicts"
git push origin

**Comment by cccbauer** [comment]
after putting all this in it says Everything up-to-date!
is that ok

**Pull request merged**
